### ISSUE TITLE
In terms of Replacement Buffer strategies, did you test random replacement?

### ISSUE THREAD

**Issue by johnrachwan123** [tyler-hayes/ExStream#1]
Hello, first of all, thank you for your great work. I see that there are ablation studies for FIFO and Reservoir sample replacement strategies. Did you test replacing incoming instances by randomly picking an instance from the buffer?

**Comment by tyler-hayes** [comment]
Hi @johnrachwan123,

Thanks for your interest in our work! We did not test a fully random replacement strategy. The closest strategy to random that we implemented was reservoir sampling (https://github.com/tyler-hayes/streaming-comparisons/blob/master/Reservoir.py).

Hope this helps!
